// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include <libintl.h>
#include "horgand_ui.h"

Rueda::Rueda(int x,int y, int w, int h, const char *label):Fl_Dial(x,y,w,h,label) {
  char tempfile[128];

sprintf(tempfile,"%s/knob.png",DATADIR);

img = Fl_Shared_Image::get((const char *)tempfile);

if (w != 50) 
   temp = img->copy(w*51,w);
   else temp= img;
}

Rueda::~Rueda() {
  img ->release();
delete temp;
}

void Rueda::draw() {
  int ox,oy,ww,hh;
int paso;
char buf[128];
float val;

ox = x();
oy = y();
ww = w();
hh = h();



  if (minimum() == maximum())
    val = 0.5;
  else {
    val = (value()-minimum())/(maximum()-minimum());
    if (val > 1.0) val = 1.0;
    else if (val < 0.0) val = 0.0;
  }


  paso = (int) (val * 47);


if (damage()&FL_DAMAGE_ALL)
{
draw_box(box(), ox, oy, ww, hh, color());
}


// if (Fl::focus() == this) box(FL_THIN_UP_BOX); else box(FL_FLAT_BOX);


draw_box(box(), ox, oy, ww, hh, color());

temp->draw(ox,oy,ww,hh,paso*ww,0);


// format(buf);

bzero(buf,sizeof(buf));

sprintf(buf,theformat,value());

draw_box(box(),ox,oy+ww,ww,hh-ww, color());

fl_font(FL_HELVETICA, 11);

fl_color(active_r() ? labelcolor() : fl_inactive(labelcolor()));

fl_draw(buf, ox, oy+ww,ww,hh-ww,FL_ALIGN_CLIP);
}

int Rueda::handle(int  event) {
  int i=0;

if (event == FL_PUSH && Fl::visible_focus()) {
    Fl::focus(this);
    redraw();
} 



switch (event) 
	{
    	              		
    		 case FL_MOUSEWHEEL :
                      {
                      if (Fl::e_dy==0) return 0;
                      handle_push();
                      handle_drag(clamp(increment(value(),Fl::e_dy)));
                      handle_release();
                      return 1;	
                      }
         
                case FL_FOCUS :
                case FL_UNFOCUS :
                      if (Fl::visible_focus()) {
                      redraw();
                      return 1;
                      } else return 0;
        }


 i = Fl_Dial::handle(event);

return i;
}

void horgand_ui::cb_ui_win_i(Fl_Double_Window*, void*) {
  Pexit=1;
}
void horgand_ui::cb_ui_win(Fl_Double_Window* o, void* v) {
  ((horgand_ui*)(o->user_data()))->cb_ui_win_i(o,v);
}

#include <FL/Fl_Pixmap.H>
static const char *idata_horgand128[] = {
"128 128 189 2",
"#s c None",
"Qt c None",
"aP c #000000",
"#. c #020505",
"#i c #050b0c",
".Y c #0f1416",
"#c c #120400",
"#3 c #130704",
".9 c #13100f",
"aT c #1a0601",
"ac c #1b0904",
".8 c #1c120e",
".X c #1d1611",
".2 c #1d2222",
"## c #22272a",
"al c #230902",
"#V c #24130c",
".W c #241b17",
".0 c #252322",
"#a c #2a3033",
"aO c #2e1007",
"#j c #2e1c17",
".1 c #2e3330",
"#o c #30150a",
"#d c #302926",
"au c #311912",
"ak c #313535",
"#k c #332317",
"aN c #361307",
"aM c #381609",
"aq c #381b0f",
"#b c #38332f",
".Z c #383c3b",
".3 c #392a24",
"aK c #3f190a",
".x c #3f2f2b",
"aL c #401c0e",
"#9 c #422317",
"#l c #422b22",
"#p c #43291a",
".y c #443d3a",
"ag c #44494a",
"as c #4a1c0c",
"ao c #4b2617",
"#h c #4b352c",
"af c #4b4f4c",
"an c #4c2e22",
"#q c #4c3425",
"#B c #4c4843",
"aJ c #511d0c",
"ap c #525356",
"#K c #533422",
"aH c #542b19",
"#e c #545857",
".v c #553e36",
"#u c #554f4c",
"aw c #57331b",
"aj c #575c5c",
".w c #5a3b2b",
"#F c #5b4530",
".V c #5b493f",
"aI c #5c2d19",
".u c #5c4139",
"a# c #5c5857",
"ad c #5e3522",
"#r c #5e6263",
"ax c #5f331b",
"#A c #5f4539",
"ay c #662f1a",
".t c #664839",
"aF c #673722",
"#2 c #673e2e",
".4 c #676463",
"#U c #676b6a",
"aG c #682d15",
"av c #683d24",
".I c #6a4b3c",
".r c #6e5249",
"aE c #6f3721",
"#T c #6f6c69",
"#S c #6f7374",
"az c #703d24",
"at c #703f2c",
"#1 c #70472e",
".s c #705143",
"#g c #705a53",
".O c #775349",
"aB c #7a441f",
"ar c #7a472c",
".H c #7a594c",
".N c #7a645f",
"#4 c #7b7876",
"#0 c #7c5834",
"aA c #7d3e24",
"aC c #7d502b",
".q c #7d5e51",
"#8 c #80513a",
"#Q c #80807e",
"aD c #814826",
"#C c #816a59",
"#P c #825c3f",
".p c #826356",
"ab c #828585",
"aS c #834a2c",
".o c #83665c",
"#G c #836c61",
"aQ c #854f2e",
"aR c #8e512f",
"aV c #905236",
"aU c #90553e",
".n c #906e60",
"aW c #915939",
"aa c #918888",
"aY c #955a2f",
".G c #95654e",
"#O c #959590",
"aX c #965f3c",
"#f c #967870",
"#n c #968179",
"#7 c #975d40",
"#Z c #976d51",
"ai c #989c9e",
"a2 c #996b3e",
".l c #997767",
"aZ c #9e674c",
"#W c #9f8163",
".k c #a07966",
"a0 c #a1633a",
"ah c #a3a7a8",
".i c #a48173",
"#v c #a4a1a0",
".m c #a57861",
"a5 c #a66d40",
".F c #a77f69",
"#N c #a79a8f",
"a1 c #a87050",
".g c #a88b84",
"#w c #abaaa6",
"#R c #abafb0",
".j c #ac8775",
".M c #ac8b7b",
"#z c #ac957c",
"#m c #ada789",
"a6 c #b27343",
".h c #b48c79",
"#6 c #b57954",
".U c #b5957b",
".L c #b59885",
".f c #b99c89",
".d c #b9a29e",
".a c #bbaca3",
"ae c #bbbcbb",
"#Y c #bc8263",
"#M c #bd9a67",
".D c #bd9d89",
".e c #bfa18f",
"#x c #bfc3c5",
".6 c #c0a793",
".E c #c5a28e",
".c c #c6b6b3",
".C c #c8a893",
"a4 c #c98e6f",
".b c #c9ac9b",
"#t c #c9c0ba",
".J c #c9c5c6",
"#L c #caad77",
"#H c #cab18a",
"#X c #ce9a75",
".B c #ceb1a3",
"#D c #cecfce",
".A c #d1baa9",
"#I c #d3bd88",
".# c #d3d7d9",
"a3 c #d8a57f",
".7 c #dac2b4",
"am c #dad9da",
".K c #ddaa88",
".P c #decbba",
".R c #e2e2e0",
"#5 c #e6eaed",
".z c #e8d4c8",
"#J c #edecee",
".T c #efe6de",
".S c #efe9da",
"a. c #eff3f8",
".5 c #f6f7f3",
"#y c #f6fbff",
"#E c #fefdf8",
".Q c #ffffff",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.a.b.c.a.d.\
d.e.e.d.f.f.f.f.e.g.e.f.g.g.h.g.g.i.i.i.j.k.k.k.i.j.i.k.l.l.l.m.l.l.l.n.n.o.p.\
p.q.q.r.r.s.t.t.u.v.u.w.v.v.x.yQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.z.c.A.B.B.B.\
b.B.C.C.e.e.D.E.E.E.e.E.d.E.e.g.h.h.h.h.h.j.F.i.j.F.i.F.k.k.k.k.m.k.l.k.k.l.l.\
n.G.n.p.G.q.H.H.r.I.I.t.I.t.u.yQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.J.b.B.B.K.b.\
B.b.C.E.E.D.D.E.E.D.D.D.E.D.L.D.h.h.h.M.h.j.h.j.i.i.k.i.F.i.k.k.k.l.m.m.l.m.l.\
n.n.p.G.N.q.H.O.O.r.t.u.t.u.v.yQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.P.b.b.b.b.b.\
b.C.C.E.E.e.D.E.E.E.D.D.D.D.h.h.L.g.h.h.j.j.j.j.i.F.i.F.k.k.k.l.l.l.l.n.n.l.n.\
G.p.G.q.O.O.O.r.r.t.u.u.u.v.v.yQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Q.R.S.z.R.S.z.T.T.T.T.S.S.c.E.C.C.b.b.\
C.C.E.E.e.D.D.E.E.E.D.D.f.h.L.U.M.h.h.M.j.j.F.F.i.i.F.i.k.F.k.l.l.l.n.n.o.p.p.\
p.H.H.O.O.O.r.O.I.V.r.I.r.v.v.x.W.X.Y.Z.0.1.1.2.W.x.3.4QtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.5.6.B.B.B.B.B.B.7.B.B.B.B.b.E.E.C.C.C.\
C.e.E.E.D.D.h.E.h.d.D.h.U.L.M.M.M.M.M.j.j.j.i.i.i.i.F.F.k.k.l.l.l.n.o.G.p.p.p.\
q.H.H.O.O.I.r.I.r.r.t.t.u.v.y.y.8.9#.##.Y#a#b.X#c#d.3#eQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.5.C.7.7.7.7.7.7.7.7.7.7.7.a.e.C.C.C.e.\
b.e.e.d.D.f.f.D.e.L.D.h.L.g.M.M.i.M.M.i.i.i.i.i.i.i.k.m.l#f#f.n#f.n.o.o.N.q.q.\
q.O#g.r.r.r.r.V.r.r.u.V.u.v.y#h.W#i#i.Y.0#b#b#j.W#k#j#eQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Q.A.P.P.P.z.z.S.z.z.z.z.z.6.e.e.e.e.e.\
e.6.e.f.f.e.e.e.f.f.g.f.L.h.g.M.i.i.i.i.i.i.i.i.i.k#f#f.l#f.l#f#f.n.o.o.q.N.q.\
N.O#g.O.r.r.r.r.V.u.r.u.u.v.v#h#j.8.9.8.W#d.3#k.3#l.3.4QtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Q.A.z.S.S.S.S.z.z.S.z.S.S.d.f.f.e.e.f.\
e#m.f.f.f.f.L.e.L.L.f.g.L.h.i.i.i.i.i.i.i#n#n.k.i.k.k#f#f.n.n.n.n.o.o.N.q.q.q#\
g.O#g.r.r.r.r.I.t.V.u.u.v.v#h#h.0.X.W.W#o#k#k#k#p#q#k#rQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt#s.Q.Q.Q.Q.T.C.7#t.P.z.P.z.z.z.z.z.P.b.e.e.e.e.e.\
e.e.f.f.f.f.D.L.D.U.L.L.L.g.i.g.i.i.i.i.i.i.i#f.l.l.n.n.n.n.n.N.o.p.p.N.q.q.q.\
H.q#g.r.r.r.r.I#u.u.u.u.v.u#h#q.0.W.0.W#k#k#j.3#k#p#l.V.a#v#w#xQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt#s.Q#y.5.Q.Q.T.B#t.z.z.z.z.z.z.z.z.z.z.D.e.e.e.e.C.\
6.6.e.e.f.f.D.f.f.D.h.L.h.g.g.h.M.g.i#z.g.i#n.l#f#f#f.n#f.n.n.n.N.N.n#g.q.N.q.\
q#g.O.O.O.O.O.O.r.t.t#A.u.v.y.y#q#j.3#l#h#B#q#b#q#q#q#C#t.J#D.PQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#s.Q.Q#E.5.Q.Q.5#t#t.P.P.z.z.z.z.z.P.A.7.e.E.b.b.C.C.\
b.6.6.6.6.f.D.f.D.h.D.f.D.h.h.g.M.M#z.M.i.i.i.i#n#f#f.n#f#f.n.n.n.N.n.n.n.N.N.\
N.N.N.H.H.H.O.O.O.O.s.r.u.u.u.v#h#q#A#A#A.V.V#F.I#A#B#G.a#H.c.A#I#tQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#x#t.5.5.S#E.5.5.R.S.T.T.T.T.T.T#J.T.S.B.b.b.B#H.C.C#\
H.B.C.6.6.6.e.C.e.f.D.D.h.g.L.L#z#z#z.M.M.M.i.g.i.i.i#f#f.n.n#f#f.n.n.n.N.n.n.\
G.n.q.N.q.q.q.H.O.s.I.I.V.u.V.w#K.n#L#M#M#M#M#M#L#L#L#L#I#I#I#M#m.V#BQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt#s.J#n.5.5.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.T.6.B.A.A.B.B.B.\
A.b.B.C.6#H.C.C.e.f.D.D.D.D.L.L.g.e#N#z.L.M.g.M.g.i.g.i#f#f#f#f#f#f#f.n#f.n.n.\
n.n.N.p.q.G.q.H.H.O.r.s.V.V#A#A#K.t#L#I#L#L#L#L#I#I#I#I#I#I#I#M#L#r#sQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt#s.J#O.R.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q#t.B.7.B.A.B.B.B.\
B.B.B.b.b.b.C.C.C.e.b.e.e.e.e.f.f.f.f.L#z#z.M.M.M.M.i.i.i.i.i.i.k#f.l.l.l.l.l.\
n#C#G.p.p.q.q#P.s.s.s#A.V.u.u.u.u#q#g#z#z#z.i.i#N.f#z#z#z#m#m#Q#z.v##QtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt#s#O#G#N#R#S#T#T#U#T#U.4#T#T#T.N.4.4.4.d.B.7.A.A.B.B.B#\
t.B.B.B.b.b.b.b.6.b.e.e.b.e.e.d.e.e.f.f.L.M.i.i.i.i.i.i.i.i.i#f#f.k.l.l.l.n.l#\
G.p#C.q.N.q.H.s#g.s.s.I#A.u.u.u.v.v#j.W.W.2.W.W.W#j.W.9.W.W.W#V.3.W#iQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt#s#t.l.a#T.y.i#W.i.F.i.j.j.U#z#z.M.M.i.b.b.b.A.B.B.B.b.\
b.b.b.b.d.C.e.e.e.e.L.L.U.U.L.L.M.h#z#z.j.i.i#f.l.l#f#f.l#f.l.l.n.n#G.o#G.q.q.\
q.H.H.s.s.s.s.I#F.V#F.u.u.v.w.v.v.v.3#k.3#j#l#q.w#K#j#V#k#p#p#V#F#q#FQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt#s#s#D.d#f.0#h.F#M.U#X.U#X#L#X#L.D#L.h.F.k.i.i.j.F#W.k.F.\
k#Y.F.m.F.F.k#W.l#W.m.l.l.m.l.l.m#Z#Z#Z.n.G#Z.G.G.q.G.G.O.G.G.O.G.O.H.H#P#0#P#\
P.s.s.s.s.s.s#0.s.s#A#1.I.I#F.u.I#2.t#F#q#o#q#h#q#l#3.8.8.3#q#3.9#B#4QtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt#s#y#5#T.8.9#k#P.G#Z#Z#Z#W#Z#Z#W#W#W.G.l.m.G.F.F#6.F.F.F.\
F#W.F.m.m#Z#Z#Z#Z#P#P#7#Z.q.G.G.p.q#Z#P.G.G#Z.q.q#P.G.O.O#8#8#8#8.H#g.s#0#0#0#\
0#F.V#A.I#F#A.w.w.u.u#F#1#F.w#1#F#F#F#F#F#9#q#q#p.3#l#p#b#k#l#o.8.8#BQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQta..5#J#4.0.9#d#C.q#0#W.U.F.F.U#M.U#z.i#G#q.I#A.I.s.i#n.n#F.\
ia#.v.u.y.l.v#A#h.w#F#4#g#G.3.y#4#l.0#d#G#u#j.3#k.3#V.3#j#j.W#n.raa#k#bab.W.Y.\
2#U#U.Y.X.9.9#B#f#n.Vac#O#r#3#3.W#m###q.Iad#F.w.t.w#2#F#P.I.w#b#V.X#oQtQtQtQt#\
sQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.R#5.5.d.W.2.9#d.H.V#k.q.F.F.m.U.F.U#W.v#B#i#r#4#4#T#D.J#O#4a\
e#Sabafaf.#ag#r#raf#eae#Oae.2af#D.1.2.Yah#r.Y.Z.X#a.Y.X.2.Y.Xaeaa#x.2.Z#x.2#i#\
iaiai#..Y#i#ia#ah#Raj#i#x#S#.#i.2#R.1.Z#F#A#1#q#A.V.w.s.s#q.v.3#3.8#k#j.v.v#s#\
sQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtaa#v.g.N#j.Y#i.Y#b#b#T#t.l#m.z#T.a#t#C.0.1.2.y.Z#e#e#S#T#U#r#\
Uaj#r.y.Z#Sag#eag.1#a#raf#e####aj.9.Y#i.Z#a.Y.2.Y.Y.Y.Y.Y.Y#iagakaf.Y.Y.Z#i#.#\
i#a.1#i#i#i#.##.Z.Z.2#iag.2#i#i.Y###e#O.Z#T#O#Babaaak#O#4.X.8.Y#i.8.X#k.W#o#V.\
0QtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.x#h#q.3.9#.#i.Yag#S#m#D#Uah.##e.R#U#4#R#O#eaeaj.##Sab#xai#Q.\
##r#Oai#r#S#raf#Q.Z#S#Qagaf#r#a#eaj###a#rafag##afaj###a.Z.2#e#e#raj#a#a#e.Y.Z#\
rag#rag.2ag#eag#Uag##.Z#eaf#e.1##ag##ag#eag.1.Z##ag.2###r#r.W.Y#i#i.Y.W.8.8al.\
0QtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtae.P.z#w.Y#i#.#i.1#a#e#Sag.##Oah.##T#r.R#Oah#xab#5#U#x#D#r#x#\
Saea.#x#e.#aj#R#Q#Sa.#5ag#x#Q#Ua..Ragah#S#Qai.Z.S.5af#Uaeaf.S.S#Uabah#e#D.Zae.\
5#m#e#5ag#R.5#R#S#Dagah#U#Q.5#Daf#x#Q#U.Sam#e#m#Q#Q#Oag.R#E#x###i#i#i.W.3.wan#\
hQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt#naa#N#n.2.2####af#eaf.1#r#D#Uahaeaf.4#Dababahab#D#r.Qa..##y.\
R#y#ya..#.Q#5a..#.R.Q#y.#a..R.R#y#y.#a..##5#5.##y.5.R.#a.am.5.Q.R.#a..##y.#a.#\
y.S.##y.##J.Q#y.#a.ama..S.R.5.5.R.5.5.#.S#E.R.Ra..R.5.R.S.Sa.#R.2#i#i.8#k#k#k#\
dQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtaa.g.g#T.Y###a#a.Zag.1##agagagag#e#aagagag.Zag#aaf#U.Q.Q.Q.Q.\
Q.Q.Q#y.Q.Q#y.Q.Q#y#y#y#y#y#ya.#y#y#y#y#y#ya.#y#ya.a.a.#Ja.a.a.a.a.a.a.a.a.a.a\
.a.a.a.#ya.a.a.a.a.a.a.a.a..R.Ra.a.a.a.a..Sa.a.a.a.a.#5a.a.a..R.Z#i#i.9#j#k#h.\
xQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt#n.n#f#u#i###e#e#eajaj#e#Uag#U#e#S#e#Sajab#r#Q#e#Q#Sai#Oaiai#\
Oabab#Q#S#U#U#U#Uafagagagagagagagagagagagagagagagag.Z.Z.Z.Z.Z.Z.Z.Z#a.Z.Z#a.Z#\
a#a#a.1.Z#a#a#a.Z#a#a.Z.Z.Z#a.Z#a.Z#a#a.Z#a.Z.Z.Z#a.Z#a.Z#a.Z#a#i#i#.#..W#V.W.\
WQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt#4#0#g.8#i.Y.2.Zag#e#e#e.1.2.2###a###a#####a.Z.Z.1#eaf#e#aag#\
aag#a#a#a#a##.2.2.Y.Y#i#i.Y#i#i#i#i#i#i#i#i#i.Y#i#i#i#i#.#.#.#.#.#.#.#.#.#.#.#\
i#.#.#.#.#.#.#.#i#i#i.Y#i.Y.Y.Y#i.Y#i#i#i#i#.#i#.#i#i#i.Y.Y#i#i#i#.#.#..9#V#o#\
hQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt#z#T###i#i#i#aab#Qah#x#R#Uah#S#D#Qae#Rahab#xah.##R#xah.#ah#5a\
e#x.#.##O#xab#U#U#aag#a.2###a.Y.2.2.Y.Y.Y.Y.Y.Y.Y.Y.Y#i#i#.#i#i#i#i#i#i#i#i#i.\
Y#i#.#i#i#i.Y#i#i.Y#i.2.Y.Y####.Y.2.Y#i##.Y#i#i#i#i#i#i.2#a.2.Y#i#.#.#.#3.W#k#\
gQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtab.f#n.1#i#i#i.Y#a#S#O#R#x#r#Q#e#S#Sag#xah#r#Qai#U#Rafaiah#Q#rae.\
Z#m.R#Q.1#O.1#e#a.2agag.Y.Y.2#i.2##.2.Y.Y.Y.Y.Y#i.2.Y#i#i#.#i#i#i#i#i#i#i#i#.#\
i#.#i#.#.#i.Y#i#.#i#.#.#.#i#i.2#i.Y.Y#i.2.Y#.#i#i#i#i#i.2.2.2#i#i#.#i#.#i.8#k#\
h.y#sQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQt.Wao.O#V#i#.#..Y#aabah#R#r#r#D#B#Rabag#U#D#rahah#S#Daf#U#R#r#Saia\
gaiai#4afaiagabagaj#Q#U.2#S#a#e#Q#U.Y#r#a#aaf.X#S#Q#####U.Yapabap.X#U.2afag###\
S#4.2ag#r.Y#S#Qag.2#U###eag.1#Q#S##aj#e.2#Q#Q.Z#a#r.2#r##.1ab#O#B#i#i#i#i.Y#ka\
qac#sQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQt.W#Kar#V#i#.#i.2#4ae#Oah#e.##w#R#5#Q#O#D#Dai#5#Oam#R#m#xahab#D#Sa\
h.Q.##e#x#Q#S#R#e.R.5#Oaj.#ag#R#E#R##.##e#4aiak#5#E#eag#D.1ah.Q#R.1aeag#O#O.Z.\
#a.aj#r.J#a#R.Q#R#aae#eabahag.#.5.4af#Dag#m#Eahag#xag#4#Q.1#t.5.#.1.Y#.#..Y#ka\
qal#sQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQt.Wasatal#i#i.2#eai#R#R#U#D#D#xae.S#m#m.R#D#D.S#D.R.R#ta..#.#.Q.J.\
5.Q#yaea.#x#5am.#.Q.Q.##Da.#x.5.5.S#x.5#x.Ram.J#E#E.R.J#y#D.T#y.5ae.T#D.R.R.J.\
5.5.T#D#y#D.T.Q#J.c#5.Sam.5#D.5#E.R#D#y.#.R#E.5#D.R.##t.S#D.S.5.5#m.Y#i#.#i#o#\
kacQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQt#daq#K.W.Y###a.Z.Zag#aag#T#e#Q#eabaf#S#U#Q#S#T#Q#4#O#D.Q.Q.Q#E.Q.\
Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q#y.Q.Q#y.Q.Q.Q.Q.Q#y#E.5#E.5#E#E.Q.Q#E.Q#E.Q.Q#y.Q.Q.Q.\
Q#E.Q.5.Q.Q.Q.Q.5#ya..Q.Q.Q.Q.Q#E.Q.Q#E.Q.5#E#y#E#E.5#E#E#E#E.5.5.5#e#.#i#.ac#\
o#3QtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQt.y#j#l.8.Wap#eaj#e#r#B#B#T#B#Q#Bab#u#m#U#n#U#e#O#Tae#t#E.T.5.R.S.\
T.R.z#t#D.J.J#x#t.a#w#v#v#Naiai#Nai#O#Oaaaaaaaaaaaaabab#n#naaaaaaabababab#naba\
b#naaabaaaa#Qaaaaaa#nabaaaaababaaabaaabababab#Qabab#Q#Q#Q#Q#Q#Q#Q#4###i#i#.#ca\
c#cQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtapau#9.W#q#g.N.l.p#f.n.l#z#W#W.n#M#W#Q#O#mag#T#m#O#m#O#N.M.L.j.j.\
h.i.k.n.n.G.G.G.G.s.O#8#1.s#1#1.t#2#2atat.t.I.t.t#2av.w.w.w#K#Kaoao#qanao#q#qa\
w#q#qao#Kan#K#hananan#K#K#Kan#h#q#q#q#q#q#q#p.3.3#l#k#k#kaq#k#k#d.W.8#3.9#3aca\
c#.QtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtau#9#j#qawaxaxayayazaAazaBaBaCaB.I.1.8#b###T#B.W.1.8.2#1aDaAaAa\
AazaraAaEaEaAaAaEaFaEaEayayaGaGaHaGaGaGaEaGaGaGaGaGaGaGaIaIaJaJaJaJaJasasaJaJa\
JasasaJaJasasasaJasaJasasaKaLaKasaLaMaMaMaKaN#o#V#o#oaOaNaNaOaOalal.9#3#Vacala\
c#3QtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt#j#k#j#kaoaHaIaxavayazaEaEayayay.t#k#.#.#.#.#i#.#.aP.9#PaQaRaSa\
SararaAarazaraEatazaEaEaEaEayayayayayayaGayaGaGayaIaIaHaHaJaJaJaJasasasasasasa\
sasasaLaKasaLaKaMaM#o#oau#o#o#o#oaOaOaOaOalal#V#Val#Valalacalalacacac#3#3#3#3a\
l#3QtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt#j#k#j.3aoaHad#K.wadad.wadavavaw.w.W#.aPaP#.#.#.aPaP#c#F#1#1ava\
vavavavavazararazataEaEaAataEaFaxaIaH#KaHaHaHanaH#KaJasaJasaJasasasasasasaKasa\
saqaLaKaMaNaNaNaNaOaO#oalal#Vacacacacacalacacacacacacacac#c#c#c#.#c#c#.ac#c#ca\
c.9QtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.8#k#k.w.t#1.u#c#.#.#cac#V#oaMaqaq#V#3#.#.#.#.#c#c#.#cacacacal#\
ValalalalaOaNaOaOaN#oaNaOaOalalalacalacalalalalalal#Valalacalalalalacacalalaca\
Tacacac#caTaTaTaT#c#c#c#c#c#c#c#.#.#c#.#.#c#.#.#c#.#.aPaPaPaPaPaPaP#3ac#3#3ac.\
9QtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.8aq#k#K#Kaoan#.#.aP#.#3#kao#9aoaoaoao#9aqaqalaOalalalalal#VaNa\
NaMaNaMaMaMaOaOalaO#Valalalacalalalalacalacacalalacacacacacac#cac#c#3acacacaca\
lac#caT#c#c#cacac#c#c#c#c#c#c#.#c#.#c#c#.#.#c#c#.#c#.aPaPaPaPaPaPaP#3ac#3#3ac.\
8QtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt#Vaq#jaoaHaoao#caPaPaP#3aqaoaHaoaJaHaHaIaJasasaLaLaKaMaNaNaMaMa\
MaKaKaMaKaKaNaNaNaN#oaOaOalaOalaOaOaOalalal#Valalalalalalal#Valal#Vacacalalala\
lalalalalalalalalalacacacacacal#3ac#3#3ac#3#3#3#.#.#.#.aPaPaPaPaP#.#V.8#3#cac#\
VQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt#Vaq.WanaEayaF.9aPaPaP#3#oaoaoaoaoaoaIaIaIaHaJaJaJasaJaKaKaMaKa\
KaMaLaLaKaMaMaNaNaKaNaNaNaO#oalaOaOalalalalalalalalaOalalalalalalalalalalalala\
Tacalalalalalalacacalacacacalacacacacac#cac#3#c#c#.#.#.aPaPaPaPaP#c#oacac#c#V.\
8QtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.8aq.WanaEayaF.9aPaPaP#i#VaLaoaoaHaHaHaHaJaJaJaJaJasasasaKaLasa\
LaLaLaLaLaKaLaMaNaNaMaNaNaNaO#oalalaOalalaOaOalaOaOaOaOaOaOalaOalalacalalacala\
calalalalalalalalalalalalalalalalalalacac#3acac#c#c#.aPaPaP#.aPaP#.acacacacala\
cQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt#Vaq#j#KayayaF#VaPaPaP#..WaqaoaHaoaHaoaHaHaHaoaJaHaJaJasaJasaLa\
saLaLaLaKaKaKaKaKaNaNaMaKaNaNaNaMaNaOaNaNaNaOaOaOaNaOaOaOaOaOaOaOalaOalalaOala\
lalalalaOalalalalalalaOaOalalalaOalacacalacalacac#c#caPaPaPaPaPaP#.#Vacacacala\
cQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.XaLaLaHaEaEaE#jaPaPaP#.#V#kaoaoaoaoaHaoaHaHaHaJaoasasasasasasa\
sasaLasaKaKaKaKaNaKaMaMaMaMaNaNaMaMaMaOaOaNaOaOaOaOalaOalaOalalaOalaOalalalala\
Oalalalalalalacalalacacacacacacacacacac#3acacac#3#c#.#.aP#.aPaPaP#cac.9#3#3ac#\
cQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.W#9aKaoaAaEaA#9aPaPaP#..8auaLaL#l#9#9aoao#9aoaoaoasasasasasasa\
sasasaLaLaLaKaMaqaOauaO#o#o#VaO#o#o#oaOaOaualaOaOalalalacalacalalalacalacalaca\
cacacacacac#cac#c#c#c#cac#c#c#c#c#c#.#c#c#c#i#c#i#.#.#.#.#i#.aPaPac#Vacac#3#3#\
cQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.xaL#9aoaAaEaA#l#.#.aP#..8auaqaqauaqauaqaq#kaqaqaLaLaKaqaqaqaqa\
qaq#oaMaMaM#o#o#oaO#V#V#V#V.8#Vac.9.8acalacacac#cacac#c#cacac#c#.#c#.#c#.#.#c#\
.#.#.#c#.#.#.aP#.#.#.#.#.#.#.#.#.#.#.#.#c#.#.#i#i#.#.#.#.#.#.aP#.acalac#3#3.9#\
.QtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.uau#9aoaAaEaAan#.#.#i.W#V#j#k.W.3ap.4#ga##ga#a#a#a#a#a#a#a#a#a\
#ap#ea#a#ajapaja#apa#a#a#a##e#eag.9#.afap.yak#ea#.2#.##ap#eaj#e#e#eapap#eap#ea\
papap#eap#e#eap#eap#e#eajapap#eap#e#e#e#e#e#eag.Y#i#i#i#s#s#.#.#.#V#Vac#3#3.9#\
cQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.4aKas#9aFayaEan.9.0#aQt#d#V.8#i#rQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Y#iQtQtQtQtQtQtag#iQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Y#.#.#i#sQt#s.Y#iacal#3#cacac#\
iQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.yaNao.x#haFaE#K.X.yQtQtak.8#caP#UQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.2#iQtQtQtQtQtQtaf#.QtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Y#.#.#iQtQtQt.2.8.8acac#c#3#3#\
.QtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt#baL#2#2aF.t#2.w#bQtQtQt#s.X.9#.#UQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.2#iQtQtQtQtQtQt#e#iQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Y#.#.#.QtQtQt#s.9.8#V#V#3.9#c#\
.QtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQta#au#K#K#K#KaoaH#sQtQtQtQt.X.9#.#rQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.2#iQtQtQtQtQtQtaj#iQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Y#.#.#iQtQtQtQt.0#V#V.8#V#3#3#\
.QtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.X#V#k#9#K#2anQtQtQtQtQt.8.9#i#rQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.0#iQtQtQtQtQtQtaf#iQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.2#.#i#iQtQtQtQtaP.8.8.9ac.9#i#\
#QtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.X#V#j#l#l#kQtQtQtQtQt.9.9ac#b.4a#a#apap#uap#uafaf.y.y.y#h.\
x.x#b#b#d#j#j#k#j#j.W.W.W#V#V.W#Valac#V.W.8.W.W.Wac#j.8#V.8.8#V.8.8.8.8.8.X.X.\
8.8.8.8.8.X.2.2.2.X.X.2.W.W###d###d.1#a#aakagag#i#.#.#iQtQtQtQtQt.9#cac#3#i.2Q\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt#a.9#j#V#3.0QtQtQtQtQt#V#V#jauau#jaMaqau#jauauauauaqaKaqaLa\
LaqaLaqaLaKaKaLaLaLaqaqauauauau#oauauaqaqaq#oaO#o#oaOalaOaOaO#oaOalal#Valalac#\
VaOalaOalalal#Val#V#Valalac#Vacac#3acac#3#c#c#c#3#.#i#iQtQtQtQtQt.2#..8.9.9.ZQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.X#d.W#iQtQtQtQtQtQt#j#9#9aq#laLaqaLaL#9aqaLaLaqaLaLasasa\
s#9aLaLaLaLaLaLaLaqaLaqaLaqaNaqaqaqaMaqaNaqaMaMaMaMaMaMaOaNaOaN#o#oaO#oaO#oaO#\
oaOaOaOaOalaO#V#Valalalalalacacacacacac#3acac#3#3#3#c.2QtQtQtQtQtQt#i.1.Y.YQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtag.W.8#iQtQtQtQtQtQt#kaoao#9aLao#lasas#9aoasaLaoasasaoaoa\
oasaoanasas#lasasasaqaLaLaLaLasasaLaLaLaLaKasaLaLaLaLaLaLaLaqaMaMaMaMaqaMaMaqa\
M#o#oaO#o#jaOaOaOaOaOaM#o#V#V#o#V#V#o#Valacacacacac#3.0QtQtQtQtQt.Z#i.Y#c##QtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt#a.y#u#c.2QtQtQtQt#s#KaoaoaH#K#KaHaHaHaHaHaHaHaHaJaHaHaHa\
HaH#KaoaJaHaHaHaHaHaoaHasasasaJasaJaoasasaLaLaLaLasaLaLaLaLaLaLaLaLaLaLaoaLasa\
LaqaqaqaqaqaqaqaMaqaqaqaMaM#k#kaqaq#o#oaO#oal#Valalac.9#sQtQtQtQt#i.9.W.9#.QtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt#j#u#B.9#iQtQtQt#s#KaFaIaxaxad#KadaIaIadadaIayadadaEaFaFa\
FaFay#KaIaI#KayaIayay#KaIaIaHaHaIaHaJaHaJasaJaJaJaHaJaoaJasasaJaHaJaoasaHasasa\
saoaoaoasaoaLaLaLasasaLasaLaLaoaLaqaqauaqaqaqau#o#o#V#o#sQtQtQtaP#i.Y#d.9#.QtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.8.3#h#3#3#sQtQt#KatazazataEaEaFaFaFaFaEaEaEaEaEaEaEaEaAa\
EaEaEaFaFaEaEaEaEaEaFayayayayayayayayaIaIaIaIaIaIaIaIaIaIaHaIaIaIaIaIaIaHaIaIa\
IaHaJaHaHaHaIaJaHaJaoaoaJaoaoaHaoaoaoaoasaL#9#9aqaqaqau#sQtQtQt#e#.#..9#c#.QtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.X#Vau#3.Y#sQt#s.tarararar#8araSaSaraAazararararararaAara\
raraAaraEaEaEaEaEaEaEaEayaEaEayaEayayayayayaIayaxaIaIayaIayaIaIayayayaIaFaIaIa\
daI#KaIadadadadaIaIadaIaxaIawawawaHaoaoaoaoaoaoaoaoaLaL#s#sQtQt.Z#.#.#.#.#.QtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.8#j#j.8.9akQt.t#8#8#8#PaUaUaUaVaWaV#PaQaQaQaVaVaVaVaVaVa\
VaVaVaSaSararararaAazarazaAataEaEaAazazaEaFayaEayayaFayayaEaFayaEayayayayaxaya\
FaFadadaFaFadadaFadadaFaFaFadadad.w#K#Kax#K#KaI#KaIaoao#s#s#sQt##aP#.#.#.aPQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.W#j#j#3#c.X.k.G.G.G.GaU.G.GaXaXaXaYaWaVaUaVaVaUaUaVaV#7a\
VaVaV#8aVaSaVaSaSaSaSaDararararatarararazazaEazazaEaEaAaEaEaEaEaEazazaEaFaFaya\
vaFaFaF#2aF#2aFaFaFaF#2at#2#2aF#2aF#2.wadaxad#K#KaH#K#p#p#s#sQt##aP#.#.#.aPQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt#d#V#o.Wac.V.k#Z.G.GaZaZ.GaZ#ZaZaXaXa0aX#7a1aZaU#7#7#7#7#\
7aVaVaVaVaVaVaRaRaDaDarararararararararararararaAaraAaraAaAaAaraAaAazat#1atata\
ratatatatatatatatatatatat.tat.tat.tatat#2.w.w#Kad#K#K#K#l#l#kQt##aP#.#.#.aPQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.y#Vau.W#d#n.Ga1a1aZa1a1a1a1a1a1a1#Z#7a2#7a1aZaZa0#7aV#7#\
7#7aVaVaRaVaRaSaSaSaSaSaRaSararaSaraSaAaAazaAaDaDaAaraBaBaraDaDaBaAaBaraSaSaS#\
8araratarararatataratatatat.t.t.tat.t#2#2avaF.wadad#K#K#9#k#V.v.9aP#.#c#.#iQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt#u#V#j#V#l.eataZ#Xa3.K.K.K.K.K.K.K#Xa3#X#X#X#Xa3a4a4a4a4#\
X#Xa4a4a4a4#Y#X#Y#Y#Y#Y#Y#Y#6#Y#Y#Y#Ya1#6a1a1a1#6a1#6#6#6a1#6a1a1a1a1a1a1a1a1a\
ZaZaZ#7aZa1aZ#7aXaXaX.GaUaUaUaUaVaUaraVaSaSararatatavaIaL#j#l.3#.#.#c#.#..2QtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt#V#o.W#3.r.h#Ya4.K.K.K.K.K.K.K.K.K.Ka3.K.Ka3.Ka3a3#Xa3a\
3a4a4#Xa4#Xa3#Xa4a4#Y#Y#Y#Y#Y#Y.m#6#6#Y#6#6#6#6#6#6#6#6#6a1a1#6#6a1a1#6a1a1a1a\
1a1a1aZa1#Za5a1#7aXaXaU.G.GaUaUaVaVaUaS#8arararatatataxao#l#o#s.YaP#.#.aP##QtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtal#o#o#.alataAaVaU#PaUaXa5aZa0#7#7a0#7aVaX#7#7a0aV#7aVa\
XaVaVaVaVaRaRaRaRaBaAaAaAaAaBaAaAaBaAaAaBaraDaDaDaDaSaSaBaBaAaAaAaDaAaAaEaEaEa\
EaEaEayaFaGaEayaIaxaGaGayaHaHaJaHaHaoaHaoasaoaoaoaLaLaL#oal#iQt#aaP#.#.#.#aQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.8#o#k#c#c#2aEarar#2aoaVa0#7a0aR#7aRaVaVaRaRaRaAaRaVaRa\
RaRaRaAaVaraBaAaAaDazaAaAaAaAaAaAaBaAazaAazavaEaBazazaEaAazazaEaEazaAaEaFataEa\
yaEatayatavaxaxaIaIaHaHaJaJaoaJaHaHasasasaJasaKaLauaqaLaq#k.9Qt##aP#.#c#.#sQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.8#j#j#c#caEaEar#0.taoaYa5aXa0aYaYaRaRaYaWaYaRaRaYaYaYa\
YaYaRaRaRaRaAaBaBaAaAaEaAaAaAaAaAaBaAaAaBavavazazazaEaAaAaEayaEaFaEaEayavataya\
EazatayayazayayaxaIaHaJaHasaHasaJaHaHaLaHaHaJaLaq#oaqaoaLaq.YQt###.#.#c#.QtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtak#j#j#c#.aFaEaB#1.IaoavaDaCaDaDaQaRaQaRaDaDaAaDaSaSaDa\
SaSaDaAaAaAaAaAaAaAaAaAaEaEaAaEaEaGaGaIaGaIaxayayayaGaIaIaIaIayayaGaIayayayaya\
yayayavaGayaxaxaIaHaJaJaHaHaHaJaHaHaoawaHaJasasaLaMaqaLaq#o##Qt##aP#c#c#iQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#j#j#c#.aFazaBaB#1asaBaW#0aRaQaBaAaraSaBaSaRaDaRaRaRa\
QaDaBaAaAaAaAaAaAaAazaEaAaEaAaAazaEaAaEaAaIaIaGavaGayaIaGaHaJaIaIaIaGayaIaIaIa\
IaIaIaIaIavaIaoaHaHaHaHaJasaJaJaJaJasaoaIasasaLaM#oaqaqaq#o.1Qt##aP#i#..YQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#j#j#3#..waAaBararaoavaD#1azazavaAaAaBaBaAaDaBaRaRaDa\
RaDaBaAaAaAaAaDaAaEaAaAaEaAaEazazazaEaEaEayayayaxaIaGaxaIaIaIaIaIaGaIaIaIaJaIa\
HaIaIaIaHaHaHaHaHaHaJaJaJasasasasasasaoaKaLaLaLaM#o#k#oaq#V#aQt.2aP#.aP##QtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#V#o#3#c#AazaB#1aCaHaBaYaBaDaDaAaBaDaDaDaDaBaBaSaRaRa\
DaSaRaDaDaBaQaAaEaAaAaAaAaAaEazaEayaEazaEayaxaGayaxavavayaxayavayayaIaIaIaIaIa\
IaIaIaJaIaIaHaJaJaJaJaHaIaJaJasasasaJaLaKasaKaLaMaqaq#o#o#V#aQt###.#.#.#aQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt#s#s.W.W#3.9.laFaBaBaraw#1aXaCaRaDaBaDaRaQaRaRaDaDaVaWaRa\
DaRaRaSaAazazatazataAaEaAaEaEaEavaGaFataFayavayaxavaxayavayaIayayaIaGaIaIaIaIa\
IaxaxaIaIaIaHaIaIaJaJaIaIaGaIaJaJaJaJaJaJaJaJasasaLaq#o#V#V##Qt###.#.#iagQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt#s#j#dac.9Qtaxarazaz#KazaX#PaCaRaDaRaRaRaRaYaVaRaY#7aRa\
RaAaRaRaQ#1azataFarararaD#8aCaraBaDaDaSataAaAaD#1aBaSaAaDaAazaEaEaEaEadayayaFa\
FavayaIaFayaIaIaGayayayaGaGaIaIaIaIaHaHaHaIaJasasaLaM#o#oac#cQt.2aP#.#.QtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#j.W.9.9#s#laEav#1#q.waW.GaX.G#PaCar#8#0#8#P#8aR#8#8a\
QaRaYaC#8.I#1#8#1.s#8#8aUaZ#Za1#7aXaX#P.Iar#PaC#1.s#8#8azavaHaxaIaHadaHaHaxad#\
K#9aoaoaoaoaoaoasaoaLasaKasas#9aLasasaqaqaoaLasaLaqaqaq#oac#3#iaPaP#.#iQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt.W.8.9Qt#KaFavaw#p#gaq#o#3#..X#i#k.s.W.9#.aq#lac#.#\
c#Vao#.#.#.#.al#.#.#.#.#c#.#.#.#.ac#.aPaP#3al#.aP#.#.#.#.aPaP#.#c#.aPaPaP#3#.a\
PaPaP#.#.aPaPaPaPaPaPaPaPac#caPaPalaL#caP#c#cacac#V#kaq#V#3#c#.aPaP#..YQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt#V.8#iQt.v.w.w#9#j#uaqau#c#..X#..8#0#j#i#.#c.3#c#.#\
.#V.w#.aPaP#..9aPaPaP#..9aPaPaPaP#3#caPaP#i#j#.aPaPaP#.#.aPaP#..8#.aPaP#.#V#.a\
PaPaP#3#.aPaPaP#.aPaPaPaP.W#.aPaP#Vaw#.aP#c#c#c#cac#j#k.W#c#.#.aPaP#.##QtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt.W.X#.Qt#uao#l#j#dQtauaqac#i.9#iaP#F#K#.aP#.#kaT#c#\
.#o.s#3aPaP#.#o#.aPaP#.#k#caPaPaP#k#3aPaP#c#p#3aPaPaP.8#.aPaP#.#j#caPaP#.#k#.a\
PaP#.#V#.aPaP#.acaPaPaP#.#k#caPaP#oaw#.aP#.#3#3#c#cac#o#V#.aPaPaPaP#.afQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#s.X.W.YQt#ban.waq##Qt#l#j#c#j.W#iaPav#1aPaP#.#p.W#i#\
..W#P#oaPaP#.aoacaPaP#caH#caPaPaPao#oaPaP#cawalaPaP#.aq#caPaP#.aoacaPaP#.aoaca\
PaP#.ao#caPaP#c#o#.aPaP#3aq#.aPaPaq#1aPaP#c#3#3#.#.#o#pacaPaPaPaPaP#.QtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt#s#s.0.W#i.y.W.u.o.u.W#s#haq#c#F#h#.#.#F#PaPaPaP.waw#.a\
P.9#PaqaP#.#cavaM#.aP#caz#VaPaPaP#qaLaPaP#.axaMaPaP#c#K#V#.aP#caIaOaPaP#.aw#Va\
P#.#cav#VaPaP#3aoalaPaP#Vav#caPaPaoaB#.#.#3.9ac#c.8#h.V#k#caPaPaPaP#.QtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt#sQt.X#d#..8#k.u.l.I#oQt.r#k.8#0#1#.#.#q#6#.aP#.#1#1#ca\
P#c.I#q#.#.#3aC#q#c#.#caQaqaPaPaPavawaPaP#.ayao#.#.acavaq#.aPacaEaqaPaP#cazaq#\
.#.#caCaq#.aPacaz#VaPaP#oaB#i#.aP#qaYac#3#3#3#c#c#V#lan#j.8#s#i#.#i#.QtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt.X#b#i.8#pad.t#Kaq.yQtau.8.s#C#.#.#q#M#o#.#.#2#P#3#\
.#i#A#1#3.8aT#P#1#c#i#.#Pao#.aPaPavavaPaPaPayaH#.#.#cavao#.aPacaAaoaPaP#.aB#q#\
.aP#caQ#kaPaP#3az#oaP#.aqaC#3#.aPawaC.W.W#3#3.8.8#j#9aq#j.WQt.2aP.Y#.QtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt.8.0.8.W.wayaEad#l#daP#kal.s#6#3#i#k#Y#K#.aP.va6#V#\
i#.#F#0ac#.#c#8#P#caP#.aQaz#.#.aPaxaB#.aPaPavaE#.aP#cadax#.aP#caAaHaPaP#.azaI#\
.aP#caQaoaPaPacaBaqaP#iaqaB#3#.aPavaC#k#b#c#3.2#bauaLaq#j.XQt##aP#.#.QtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt#j.3#j#j.wayaraxao.WaP#kac#0#M.8#3.Wa5#1#3#i#ha6aM#\
.#..wa2#V#.#.#1a2#V#.#.#0aC#.aPaPaHaC#caPaPaxaB#.aP#.adav#.aP#caBaw#.aP#.azav#\
.aP#caQawaPaP#3aDaqaP#.aoaC.9aPaPawaY.3#b#3#3#B#s#kao#9#j.0Qt.2#.#i#.QtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt#j.3#j#k#KaFataF#9.XQt#k#3#0#L#k.8.8a2#P.8#i#k#M#q#\
.#.aoa2#k#.#.ava5#o#.#.#0aC#caPaP#qaYaTaP#.axaD#.aP#..w#1#caP#caCav#.aP#.#1aB#\
caP#caQ#qaPaPacaBaqaP#.#p#0.8aPaPav#0.3#h#3.9QtQt#oao#p#VakQt.X#3#.#iQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt.W#k.3#d.uadataF#p.WQt.3#V#q#L#F.8.8#P#Y#V#3#Va6#1#\
3#.#oa5#q#i#i#qa5#q#.#c#0aY#3aPaP#qaYalaPaPaxaQ#caPaP#FaC#3aP#caCaB#caP#.azaB#\
caP#caYavaPaPacaBaqaP#.aoa2#VaPaPavaC#q.1#3.9QtQt#kao#9#V.ZQt.2#i#.#.QtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#s.W#l#l#daPaJaF#2ao##Qt.3#k#k#M#0.8.2#F#Mao#i.8a5#0#\
3#..9a5#1aP#.aoa5av#.#.#1a0#VaPaPaoaY#oaPaPaIaY#oaPaP#qaYacaP#iaCaC#caP#.azaC#\
3#.#.aYaz#.#.acaBaoaP#.aoa2#VaP#cavaY#F###V.WaP#saqao#9#VQtQt#a#.#.#iQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt.Z.3.3##Qt#Kav#2#p#dQt.Zac.V#L#0.W.Y.3#M#q.9.8#Pa2.\
8#.#.a5aB#.#.#ka5avaP#.awa2#VaP#.aqa0aqaPaPaoaYaqaPaPaoaY.8aP#.#1aCacaP#.avaY#\
3aP#3aYaB#.aP#3aBaoaPaP#p#P#o#.#.avaD.V#d#3.8QtQt#oao#9#VQtQtQt#.#.#.QtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt#j#j#dQt.tadavan.yQt.Zal#j#Ma2#3.8#k#MaB.9.8#0a5#\
kaP#.aX#P#c#i#Va2aC#.aP#qa0#o#.#.#Va0aoaPaPaqa0aoaPaPaqa2#oaP#.#1#0#VaP#.azaYa\
caP#.aYaB#.#.acaD#qaP#.#qa2#VaP#.avaC#F.0#3.YQtQt#kaoao.WQtQtQt#i#i#aQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt#s#s.W#d.2Qt#gaxad#KQtQt.3.3#3#P#M.8#V.8#M#P#i.8#1a1#\
p#.#i#0a0#V#.#3a2aY#c#.aqa5aoaPaP#Va2#qaP#.#Va0aoaPaPaqa2aqaP#.avaY#VaP#cavaYa\
caP#c#0aD#3aP#caBaxaPaP.3#P#VaP#.avaB#h.9.W.8#s#s#Vaoaq.ZQtQtQt#i#iQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.0##.2QtQt#K#F#pQtQtaq#V#i#Fa5#k.8#i#Ma2#3#i#q#6a\
w#.#.#Aa5#V#.#.#Pa0#c#.aqa5avaPaP.9aYav#.aP#Va0aHaP#.#Va2aL#.#.avaYaqaPaPaIaYa\
caP#.#0aC#3aP#caBaxaP#.#kaY#kaP#.azaC#F#.#i#.#s#s#Vao#jajQtQtQt#i#iQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtaj#aQtQtQt#Kat#pQtQt.v.3#..8#8#q#3#.a5#Y#3#i#k#Ya\
B#.#i#Fa5aqaPaPaCa5al#.#Va5avaPaPacaXav#caP.9aYav#.aP#VaXaoaPaPawaYaMaP#.aIaY#\
VaP#.aCaC#3aP#caBaxaPaP#paC#kaP#.avaB.3#i#.#c#sQt#kao#VQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.waFanQtQt.w#VaP#Va5.I#3#ia2#Maq#3ac#Ma\
2#..9#q#Yav#.aP#1a5#o#c#ca5aE#.#.acaY#0ac#.#VaYav#.#.aca2axaP#.awa2aqaPaPawaY#\
VaP#.#1aY#caP#caBavaPaP#kaW#kaP#.av#1#k#iaP#c#sQt#o#p#VQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.r#2anQtQt#hal.8#j#1aw#V.Waw#Pao#o#V#P#\
0ac.9aq#0.3#c#c#paB#V#3#cavaw#c#.acavaval#cacawao#c#cac.wao#.#.aqad#V#.#.aMaw.\
8#.#.#q#F#caP#caq#o#.aP#oaw#VaP#.aLao.8#.#.#.#sQt#kao.WQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtaFan.N.l#k.8#V#V#oaMaq#kaqaqaqaqaqaMa\
L#o#o#o#o#V#V#V#Valalacacacacac#3acacac#3#3#calac#caT#3aTaT#3#c#c#c#c#.#.#.#.#\
c#.#.#c#c#.#.#.#c#c#c#.#.#c#c#.#.#c#c#c#.#.#..0Qt#k#p.WQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#Kao#u.O#V#j#k#oaqaqaqaLaqaLaqaKaLaM#\
o#o#V#V#o#V#oaOalal#Vacacacacacacal#3acacacac#3alacac#cacac#c#c#c#c#c#.#.#c#.#\
.#c#.#c#c#c#.#c#.#.#.#.#c#c#.#.#.#c#.#.#.#c#..8.y#9#k#hQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#K#K#k.tac#V#V#VaqaMaLaLaLasaKaqaLaMa\
N#o#oaq#o#V#V#Valalacacalacalalacacacacacacacacacacal#3ac#cac#c#c#c#c#c#c#.#c#\
c#c#c#c#c#c#c#c#.#.#.#c#c#c#c#.#c#.#.#.#.#c#.#3#oaq#kapQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#K#Kau#h.8aqaMaqaLaLaoaoaLaqaLaqaqaq#\
o#o#o#o#o#o#V#o#Valacacalacacacalalalalacalal#3acacal#c#c#c#c#c#c#c#3#c#c#c#c#\
c#c#c#c#c#c#.#.#c#.#.#.#c#.#.#caP#.#.#.#.#.#.#.acaq#Va#QtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.w#Kal.8#VaLasasasasaoaoasasaLaqaLaqa\
qaMaq#o#oaqaM#o#o#V#oal#Valal#Valalalalalacalalacal#cac#cac#cacaT#c#c#c#c#c#c#\
c#c#c#c#c#c#c#c#.#c#c#c#.#c#c#.#c#.#.#.#c#.#.#.acao#k#bQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.u.u#o#3#oaoaoaJaoaoaoaoaoasaoaoaqaKa\
KaKaLaLaMaLaqasaO#j#oaN#VaNaOaOaOaOaOaOaOaOalalalalalalacacalac#cacac#3acac#ca\
c#c#c#cac#c#c#c#cal#3#3ac#c#c#c#c#c#c#c#c#c#.#.alan#k.yQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#laqac#i.8ao#9#p#9#pao#paoasaoaoaoaoa\
oaoaoaH#Kaoao#laoaoaoaoaoaqaLaMaMaqaLaMaMaMaOaN#o#o#o#V#V#V#V#o#o#o#o#V#Valala\
lacalalalalalacalalacalalalac#c#c#c#c#.#.#.#.aP#caq.8QtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#k#9#V.9#jaoaq#kauaqaMaMaqaqaMaMaNaMa\
qaMaq#o#o#oaq#j#o#o#oal#oaO#V#Val#oalalalalalalalacacacac#3acacal#Valacacacaca\
calac#cacacacacacac#cacac#cac#c#c#c#c#.#c#c#c#..9#k.XQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtan.u#k.9#l.waxaxad.wavaEavazazaEaFaEa\
E#1#1aEazaEazavazaF#KaHay#K#2adadaHawawawaHawaHawawawawawaw#K#qaHaHaoaHaoaoaoa\
HaHaHaoasaJaJasaJasasasasasaLasaqaKaqaqaq#o#V.9#j#l.W.yQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtan.w#q.8#kadaF.wadaxayayayayayayaEaFa\
EazaAazazazazazaB#1an#KaEaJavataFadadayavavayaIavaIaxavaxayaxaIayaIaHaIawaIaIa\
vaxawawaHaIaIaIaIaIaHaHaHaJasasasasaoaoaLaL#o.8#o#l.8.0QtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#qaw#h.9#jax#Kad.wadayayavayayavavava\
v#1az#2azavazaEavav#KadaFaHavaFadaIaxadaIaxaxavaxaIaxaxaxaxaxaIaxaIawaHaHaxaIa\
waHaIaHaHaIaHaHaHaoaoaoasaLaLaLaKaL#paLaLaL#o.8#oaL.W.WQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtanaH.wQt#B#ladavaFaxaIayavayavayayava\
vaIaIaIaxayayaFayaIaoaIayaIaIaIaIaHawawawaHaHaHaHawaHaoaoaoaoaoaoaoaJasasaoasa\
saoaHaoaoaoaoasasasaLasasaLaLaLaLaLaLaqaMal#d.Z#j#jal#dQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#kad#KQtQt#k.w.wavar#1atataA#1#1#1ara\
ravatatazarararaEaFayaEaEazaFayaxayayavaIaxaHaHaHaIawaHawawawaIaIaIawaHaHaxaHa\
xaxavaHaIaHaIaHaHaHaHaHaJaJaHaoaHaHaHaLaq.8.ZQt#k#kal.yQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.yan#lQtQt.0#h.t.t.t.t.O#2#2#2atataFa\
d#K#K#2aF#2atataFadaFaFaEaz#2adaFaFadaxaxaHaHaxaxayaIawawaIaIaIawaxaI#KaoaHaHa\
dayadaJaIaHaIaHaoaHaHaJaJasaJasasaJaHaLau#3agQt#d#j#VQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#uan#kQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#j#k.WQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtan#lQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.W.0QtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtan#kQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#jakQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.r.yQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.2.2QtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQ\
tQtQtQtQtQtQtQtQtQtQtQt"
};
static Fl_Pixmap image_horgand128(idata_horgand128);

void horgand_ui::cb_Load_i(Fl_Menu_*, void*) {
  char *filename;
filename=fl_file_chooser("Browse:","(*.horeb)",DATADIR,0);
if (filename==NULL) return;
filename=fl_filename_setext(filename,".horeb");
setBankFile->copy_label(filename);
strcpy(uBankFilename,filename);
ready=1;
}
void horgand_ui::cb_Load(Fl_Menu_* o, void* v) {
  ((horgand_ui*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

Fl_Menu_Item horgand_ui::menu_[] = {
 {gettext("&File"), 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {gettext("Load Bank"), 0,  (Fl_Callback*)horgand_ui::cb_Load, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

void horgand_ui::cb_D_Vol_i(Rueda*, void*) {
  D_Vol_c=1;
}
void horgand_ui::cb_D_Vol(Rueda* o, void* v) {
  ((horgand_ui*)(o->parent()->user_data()))->cb_D_Vol_i(o,v);
}

void horgand_ui::cb_D_Tune_i(Rueda*, void*) {
  D_Tune_c=1;
}
void horgand_ui::cb_D_Tune(Rueda* o, void* v) {
  ((horgand_ui*)(o->parent()->user_data()))->cb_D_Tune_i(o,v);
}

void horgand_ui::cb_PresetSelect_i(Fl_Choice*, void*) {
  ready=2;
}
void horgand_ui::cb_PresetSelect(Fl_Choice* o, void* v) {
  ((horgand_ui*)(o->parent()->user_data()))->cb_PresetSelect_i(o,v);
}

horgand_ui::horgand_ui() {
  fl_open_display();
Fl::visual(FL_DOUBLE|FL_RGB);
fl_register_images();
make_window();
ui_win->xclass("horgand-dssi");
ready=1;
ui_win->show();
void * v=MT;
Fl::add_timeout(1.0 * 0.04,tick,v);
}

Fl_Double_Window* horgand_ui::make_window() {
  { ui_win = new Fl_Double_Window(330, 280);
    ui_win->color((Fl_Color)147);
    ui_win->callback((Fl_Callback*)cb_ui_win, (void*)(this));
    { Fl_Box* o = new Fl_Box(170, 49, 165, 116);
      o->image(image_horgand128);
      o->labelsize(18);
    } // Fl_Box* o
    { setBankFile = new Fl_Box(5, 257, 330, 18, gettext("Default"));
      setBankFile->labelsize(9);
      setBankFile->labelcolor((Fl_Color)3);
    } // Fl_Box* setBankFile
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 345, 25);
      o->labelsize(18);
      o->textsize(18);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { d_osc_label = new Fl_Box(0, 23, 330, 21);
      d_osc_label->labelsize(9);
      d_osc_label->labelcolor((Fl_Color)3);
    } // Fl_Box* d_osc_label
    { Fl_Box* o = new Fl_Box(170, 198, 160, 22, gettext("<c> 2004-2009 by Josep Andreu"));
      o->labelsize(9);
      o->labelcolor((Fl_Color)FL_BACKGROUND2_COLOR);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(185, 166, 145, 29, gettext("Horgand"));
      o->labelfont(1);
      o->labelsize(21);
      o->labelcolor((Fl_Color)FL_BACKGROUND2_COLOR);
    } // Fl_Box* o
    { MT = new Fl_Box(85, 243, 120, 16);
      MT->labelsize(11);
    } // Fl_Box* MT
    { Rueda* o = D_Vol = new Rueda(20, 100, 50, 60, gettext("Volume"));
      D_Vol->box(FL_FLAT_BOX);
      D_Vol->color((Fl_Color)147);
      D_Vol->selection_color((Fl_Color)FL_INACTIVE_COLOR);
      D_Vol->labeltype(FL_NORMAL_LABEL);
      D_Vol->labelfont(0);
      D_Vol->labelsize(11);
      D_Vol->labelcolor((Fl_Color)FL_BACKGROUND2_COLOR);
      D_Vol->step(0.01);
      D_Vol->value(1);
      D_Vol->callback((Fl_Callback*)cb_D_Vol);
      D_Vol->align(FL_ALIGN_TOP);
      D_Vol->when(FL_WHEN_CHANGED);
      strcpy(o->theformat,"%1.2f");
    } // Rueda* D_Vol
    { Rueda* o = D_Tune = new Rueda(20, 185, 50, 60, gettext("Master Tune"));
      D_Tune->box(FL_FLAT_BOX);
      D_Tune->color((Fl_Color)147);
      D_Tune->selection_color((Fl_Color)FL_INACTIVE_COLOR);
      D_Tune->labeltype(FL_NORMAL_LABEL);
      D_Tune->labelfont(0);
      D_Tune->labelsize(11);
      D_Tune->labelcolor((Fl_Color)FL_BACKGROUND2_COLOR);
      D_Tune->minimum(-1);
      D_Tune->step(0.01);
      D_Tune->callback((Fl_Callback*)cb_D_Tune);
      D_Tune->align(FL_ALIGN_TOP);
      D_Tune->when(FL_WHEN_CHANGED);
      strcpy(o->theformat,"%1.2f");
    } // Rueda* D_Tune
    { PresetSelect = new Fl_Choice(5, 60, 150, 20, gettext("Preset"));
      PresetSelect->box(FL_PLASTIC_DOWN_BOX);
      PresetSelect->down_box(FL_FLAT_BOX);
      PresetSelect->color((Fl_Color)31);
      PresetSelect->selection_color((Fl_Color)147);
      PresetSelect->labelsize(11);
      PresetSelect->labelcolor((Fl_Color)FL_BACKGROUND2_COLOR);
      PresetSelect->textsize(9);
      PresetSelect->callback((Fl_Callback*)cb_PresetSelect);
      PresetSelect->align(FL_ALIGN_TOP);
      PresetSelect->when(FL_WHEN_CHANGED);
    } // Fl_Choice* PresetSelect
    ui_win->end();
  } // Fl_Double_Window* ui_win
  return ui_win;
}

void horgand_ui::tick(void* v) {
  Fl_Box *o = (Fl_Box*)v;
o->do_callback();
Fl::repeat_timeout(1.0 * 0.04,tick,v);
}
