// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef horgand_ui_h
#define horgand_ui_h
#include <FL/Fl.H>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../config.h"
#include <FL/Fl_Shared_Image.H>
#include <FL/Fl_Valuator.H>
#include <FL/Fl_Dial.H>
#include <FL/Fl_Box.H>
#include <FL/fl_draw.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/x.H>

class Rueda : public Fl_Dial {
public:
  char theformat[32]; 
  Fl_Shared_Image *img; 
  Fl_Image *temp; 
  Rueda(int x,int y, int w, int h, const char *label=0);
  ~Rueda();
  void draw();
  int handle(int  event);
};
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Choice.H>

class horgand_ui {
public:
  int ready; 
  int D_Vol_c; 
  int D_Tune_c; 
  int Pexit; 
  int Pexitprogram; 
  char uBankFilename[255]; 
  horgand_ui();
  Fl_Double_Window* make_window();
  Fl_Double_Window *ui_win;
private:
  void cb_ui_win_i(Fl_Double_Window*, void*);
  static void cb_ui_win(Fl_Double_Window*, void*);
public:
  Fl_Box *setBankFile;
  static Fl_Menu_Item menu_[];
private:
  void cb_Load_i(Fl_Menu_*, void*);
  static void cb_Load(Fl_Menu_*, void*);
public:
  Fl_Box *d_osc_label;
  Fl_Box *MT;
  Rueda *D_Vol;
private:
  void cb_D_Vol_i(Rueda*, void*);
  static void cb_D_Vol(Rueda*, void*);
public:
  Rueda *D_Tune;
private:
  void cb_D_Tune_i(Rueda*, void*);
  static void cb_D_Tune(Rueda*, void*);
public:
  Fl_Choice *PresetSelect;
private:
  void cb_PresetSelect_i(Fl_Choice*, void*);
  static void cb_PresetSelect(Fl_Choice*, void*);
public:
  static void tick(void* v);
};
#endif
